apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
  - port: 21
    name: ftps
    protocol: TCP
    targetPort: 21
  - port: 30000
    name: pass
    protocol: TCP
    targetPort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000